### ISSUE TITLE
运行yolov4的export报错

### ISSUE THREAD

**Issue by yuedongli1** [mindspore-lab/mindyolo#112]
### Hardware Environment(`Ascend`/`GPU`/`CPU`): 
> Uncomment only one ` /device <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> `/device ascend`</br>

### Software Environment:
- **MindSpore version (source or binary)**:
- **Python version (e.g., Python 3.7.5)**:
- **OS platform and distribution (e.g., Linux Ubuntu 16.04)**:
- **GCC/Compiler version (if compiled from source)**: 

## Describe the current behavior
Traceback (most recent call last):
  File "./deploy/export.py", line 84, in <module>
    export_weight(args)
  File "./deploy/export.py", line 68, in export_weight
    checkpoint_path=args.weight,
  File "/home/ma-user/work/mindyolo-master/mindyolo/models/model_factory.py", line 30, in create_model
    model = create_fn(**model_args, **kwargs)
  File "/home/ma-user/work/mindyolo-master/mindyolo/models/yolov4.py", line 41, in yolov4
    model = YOLOv4(cfg=cfg, in_channels=in_channels, num_classes=num_classes, **kwargs)
  File "/home/ma-user/work/mindyolo-master/mindyolo/models/yolov4.py", line 24, in __init__
    self.model = build_model_from_cfg(model_cfg=cfg, in_channels=ch, num_classes=nc, sync_bn=sync_bn)
  File "/home/ma-user/work/mindyolo-master/mindyolo/models/model_factory.py", line 45, in build_model_from_cfg
    return Model(**kwargs)
  File "/home/ma-user/work/mindyolo-master/mindyolo/models/model_factory.py", line 52, in __init__
    deepcopy(model_cfg), ch=[in_channels], nc=num_classes, sync_bn=sync_bn
  File "/home/ma-user/work/mindyolo-master/mindyolo/models/model_factory.py", line 193, in parse_model
    m_ = nn.SequentialCell([m(*args, **kwargs) for _ in range(n)]) if n > 1 else m(*args, **kwargs)
  File "/home/ma-user/work/mindyolo-master/mindyolo/models/layers/bottleneck.py", line 12, in __init__
    c_ = int(c2 * e)  # hidden channels
TypeError: unsupported operand type(s) for *: 'int' and 'Mish'

## Steps to reproduce the issue
1. python ./deploy/export.py --per_batch_size=1 --file_format AIR --config ./configs/yolov4/yolov4.yaml --weight ./ckpt/yolov4-cspdarknet53_320e_map454-50172f93.ckpt
2. 
3.

**Comment by yuedongli1** [comment]
传入参数没有对齐导致，已经修改为key=value形式传入act参数
