### ISSUE TITLE
基于WSL2系统在GPU上训练时的问题

### ISSUE THREAD

**Issue by wenlongli10** [mindspore-lab/mindyolo#214]
当前mindyolo不支持GPU训练吗？我在训练yolov8n时有一些报错，这是哪方面的报错？
Traceback (most recent call last):
  File "/mnt/c/Program Files/JetBrains/PyCharm 2022.3/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_comm.py", line 293, in _on_run
    r = self.sock.recv(1024)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/mnt/c/Program Files/JetBrains/PyCharm 2022.3/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_comm.py", line 293, in _on_run
    r = self.sock.recv(1024)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/mnt/c/Program Files/JetBrains/PyCharm 2022.3/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_comm.py", line 293, in _on_run
    r = self.sock.recv(1024)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/mnt/c/Program Files/JetBrains/PyCharm 2022.3/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_comm.py", line 293, in _on_run
    r = self.sock.recv(1024)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/mnt/c/Program Files/JetBrains/PyCharm 2022.3/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_comm.py", line 293, in _on_run
    r = self.sock.recv(1024)
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by kill2013110** [comment]
master分支可以用了吗

**Comment by kill2013110** [comment]
目前yolox nano是可以用的，包括图模式训练

**Comment by kill2013110** [comment]
目前我在r0.2版本上用yolox-tiny是可以进行图模式和动态图模式训练的

**Comment by zhanghuiyao** [comment]
上面的报错看起来是pycharm的debug功能相关的报错，可以试下直接在terminal窗口里面用命令行执行试一下

**Comment by zhanghuiyao** [comment]
> master分支可以用了吗

可以用

**Comment by kill2013110** [comment]
> 上面的报错看起来是pycharm的debug功能相关的报错，可以试下直接在terminal窗口里面用命令行执行试一下

是的是的，没注意看到😂

**Comment by kill2013110** [comment]
optimize 'per_batch_map' 这个是个啥参数

**Comment by zhanghuiyao** [comment]
> optimize 'per_batch_map' 这个是个啥参数

这个说的是dataloader中的per_batch_map吗，这个是数据处理后面将数据组织成batch的操作，具体的可以参考[文档](https://www.mindspore.cn/docs/zh-CN/master/api_python/dataset/dataset_method/batch/mindspore.dataset.Dataset.batch.html#mindspore.dataset.Dataset.batch)
