### ISSUE TITLE
转换成mindir文件后想应用部署上线但一直部署失败，报错日志如下

### ISSUE THREAD

**Issue by HwangYunJin** [mindspore-lab/mindyolo#259]
[2024-01-04 09:05:14 +0800] [46] [INFO] Starting gunicorn 20.1.0
[2024-01-04 09:05:14 +0800] [46] [INFO] Listening at: http://172.16.0.78:8443 (46)
[2024-01-04 09:05:14 +0800] [46] [INFO] Using worker: gthread
[2024-01-04 09:05:14 +0800] [49] [INFO] Booting worker with pid: 49
start. . .
2024-01-04 09:05:14 CST [MainThread ] - /home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/model_service/app.py[line:50] - INFO: args: Namespace(model_name='serve', model_path='/home/ma-user/infer/model/1', service_file='', tf_server_name='127.0.0.1')
[2024-01-04 09:05:14 +0800] [49] [ERROR] Exception in worker process
Traceback (most recent call last):
File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
worker.init_process()
File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
super().init_process()
File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
self.load_wsgi()
File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
self.wsgi = self.app.wsgi()
File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
self.callable = self.load()
File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
return self.load_wsgiapp()
File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
return util.import_app(self.app_uri)
File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/gunicorn/util.py", line 359, in import_appmod = importlib.import_module(module)
File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "

**Comment by zhanghuiyao** [comment]
可以尝试下 MSLite 方式部署，文档参考如下：
https://github.com/mindspore-lab/mindyolo/tree/master/deploy
