### ISSUE TITLE
yolov8执行test.py报错

### ISSUE THREAD

**Issue by lilero** [mindspore-lab/mindyolo#306]
(MindSpore) [ma-user mindyolo-0.3]$python test.py --config /home/ma-user/work/mindyolo-0.3/config.yaml --weight /home/ma-user/work/mindyolo-0.3/runs/2024.07.09-19.24.32/weights/config-100_1172.ckpt
Traceback (most recent call last):
  File "/home/ma-user/work/mindyolo-0.3/test.py", line 12, in <module>
    from pycocotools.coco import COCO
  File "/home/ma-user/modelarts-dev/common-algo-toolkit/pycocotools/coco.py", line 52, in <module>
    from . import mask as maskUtils
  File "/home/ma-user/modelarts-dev/common-algo-toolkit/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
ModuleNotFoundError: No module named 'pycocotools._mask'

**Comment by yuedongli1** [comment]
可参考https://github.com/cocodataset/cocoapi/issues/272
