### ISSUE TITLE
demo/predict.py  run error

### ISSUE THREAD

**Issue by MouseSun846** [mindspore-lab/mindyolo#336]
```
(MindSpore) [ma-user mindyolo]$python demo/predict.py --config ./configs/yolov3/yolov3.yaml --weight=/home/ma-user/yolov7-x_300e_mAP524-e2f58741.ckpt --image_path /home/ma-user/work/dog.jpg
Traceback (most recent call last):
  File "demo/predict.py", line 335, in <module>
    infer(args)
  File "demo/predict.py", line 274, in infer
    set_default_infer(args)
  File "demo/predict.py", line 57, in set_default_infer
    ms.set_context(jit_config={"jit_level": "O2"})
  File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/_checkparam.py", line 1319, in wrapper
    return func(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/context.py", line 1410, in set_context
    raise ValueError(f"For 'context.set_context', the keyword argument {key} is not recognized! For detailed "
ValueError: For 'context.set_context', the keyword argument jit_config is not recognized! For detailed usage of 'set_context', please refer to the Mindspore official website
```
Refer to the guide file, running demo/edict.py will result in an error. How can I solve it？

```
python demo/predict.py --config ./configs/yolov3/yolov3.yaml --weight=/home/ma-user/yolov7-x_300e_mAP524-e2f58741.ckpt --image_path /home/ma-user/work/dog.jpg
```

**Comment by qpq187** [comment]
我也遇到了相同的问题
![image](https://github.com/user-attachments/assets/0eb1e7eb-3030-4253-994f-cac1eb9f6854)

**Comment by Goofoffdog** [comment]
我也出现过同样的问题，我的解决办法是将predict.py文件中的    
if args.ms_mode == 0:
   '''ms.set_context(jit_config={"jit_level": "O2"})'''
这行代码注释掉(不要使用#号注释，使用'''注释)即可运行出结果，结果存放在mindyolo-master的runs_infer文件夹下面。

**Comment by WongGawa** [comment]
感谢反馈。请提供一下环境所使用MindSpore版本信息，以及所使用的MindYolo版本信息。
可以参考如下链接提前排查。
[version info](https://github.com/mindspore-lab/mindyolo/blob/master/README.md?plain=1#L18)

**Comment by MouseSun846** [comment]
我这边定位是环境依赖问题，通过进程通信方式解决了。
