### ISSUE TITLE
A bug for yoloV5&yoloV8 in Ascend Training, seems like mindspore code issue：For Stack, all types should be same, but got (mindspore.tensor[float32], mindspore.tensor[float32], mindspore.tensor[float32], mindspore.float32)

### ISSUE THREAD

**Issue by doubtfire009** [mindspore-lab/mindyolo#340]
我在使用昇腾Ascend: 8*ascend-snt9b测试自定义数据集的detection任务，使用yolov5及yoloV8。

按照https://github.com/mindspore-lab/mindyolo/blob/master/examples/finetune_car_detection/README.md 生成的数据集，需要图像和label一一对应，数量必须一致。

在训练过程中，发现一个error，
Traceback (most recent call last):
  File "/home/ma-user/work/mindyolo/train.py", line 320, in <module>
    train(args)
  File "/home/ma-user/work/mindyolo/train.py", line 275, in train
    trainer.train(
  File "/home/ma-user/work/mindyolo/mindyolo/utils/trainer_factory.py", line 170, in train
    run_context.loss, run_context.lr = self.train_step(imgs, labels, segments,
  File "/home/ma-user/work/mindyolo/mindyolo/utils/trainer_factory.py", line 366, in train_step
    loss, loss_item, _, grads_finite = self.train_step_fn(imgs, labels, True)
  File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.9/site-packages/mindspore/common/api.py", line 718, in staging_specialize
    out = _MindsporeFunctionExecutor(func, hash_obj, input_signature, process_obj, jit_config)(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.9/site-packages/mindspore/common/api.py", line 121, in wrapper
    results = fn(*arg, **kwargs)
  File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.9/site-packages/mindspore/common/api.py", line 350, in __call__
    raise err
  File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.9/site-packages/mindspore/common/api.py", line 344, in __call__
    phase = self.compile(self.fn.__name__, *args_list, **kwargs)
  File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.9/site-packages/mindspore/common/api.py", line 435, in compile
    is_compile = self._graph_executor.compile(self.fn, compile_args, kwargs, phase, True)
  File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.9/site-packages/mindspore/ops/operations/array_ops.py", line 3036, in __infer__
    all_shape = _get_stack_shape(value, x_shape, x_type, self.axis, self.name)
  File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.9/site-packages/mindspore/ops/operations/array_ops.py", line 2954, in _get_stack_shape
    raise TypeError(f"For {prim_name}, all types should be same, but got {x_type}")
TypeError: For Stack, all types should be same, but got (mindspore.tensor[float32], mindspore.tensor[float32], mindspore.tensor[float32], mindspore.float32)

打了日志查看输入数据类型，发现输入并没有问题，所以请昇腾的技术同事帮忙检查有什么问题？

![3d103f96df5920131043c6fd785591d](https://github.com/user-attachments/assets/d59d9af3-328b-40a3-a0fb-efa2d66bc676)

训练命令是：
python train.py --config ./configs/yolov5/yolov5_frame.yaml --device_target Ascend --ms_mode 1

**Comment by yuedongli1** [comment]
mindyolo套件目前只支持graph模式训练，可尝试删除参数--ms_mode 1

**Comment by doubtfire009** [comment]
![image](https://github.com/user-attachments/assets/f7fccf17-fff0-457d-afae-0268509200f4)
不加ms_mode，也出现了这个问题。另外，我在utils.py里面把
![image](https://github.com/user-attachments/assets/bfd4afaf-396c-4693-a5cd-13354d55f001)
这个zhu注释了，因为https://gitee.com/mindspore/mindspore/issues/IAEDX0 里面讲了jit仅支持MindSpore-2.3以上版本

**Comment by doubtfire009** [comment]
我自己又测试了一下，发现问题出在：1. 需要使用匹配的环境和mindyolo版本。我使用了mindyolo0.2.0和 mindspore_2.1.0-cann_6.3.2-py_3.7-euler_2.8.3-aarch64-d910  2.  ![image](https://github.com/user-attachments/assets/d353d4dc-9c07-474d-9819-04a741c8c97a) 需要按照截图增加一句代码，就可以跑通。


![image](https://github.com/user-attachments/assets/d15773a8-397d-40e6-a874-fd6c15092861)

**Comment by doubtfire009** [comment]
该问题经过自己的调整解决
